name: Build

on:
  schedule:
    - cron: 6 */8 * * *
  #  push:
  #    branches:
  #      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - userName: q215613905
            repoUrl: https://github.com/q215613905/TVBoxOS
            branchName: main
            javaVersion: 8

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Source Code
        run: |
          git clone --depth=1 -b ${{ matrix.branchName }} ${{ matrix.repoUrl }} bgcode

      - name: Add Sign Info
        run: |
          cp -f ${{ github.workspace }}/actions/.github/bgcode.jks ./app/bgcode.jks
          sed -i '$a\RELEASE_STORE_FILE=./bgcode.jks'     ./gradle.properties
          sed -i '$a\RELEASE_KEY_ALIAS=bgcode'            ./gradle.properties
          sed -i '$a\RELEASE_STORE_PASSWORD=bgcode'       ./gradle.properties
          sed -i '$a\RELEASE_KEY_PASSWORD=bgcode'         ./gradle.properties


      - name: Build With Gradle
        run: |
          cd bgcode
          chmod +x gradlew
          ./gradlew assembleRelease --build-cache --parallel --daemon --warning-mode all

      - name: Prepare App
        run: |
            cd bgcode
            mkdir -p ${{ github.workspace }}/apk/
            for file in `find ~ -name "*.apk" -print`; do
              mv "$file" ${{ github.workspace }}/apk/
            done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
            name: bgcode
            path: bgcode/${{ github.workspace }}/apk/*
 
