name: Build

on:
  schedule:
    - cron: 6 */8 * * *
  #  push:
  #    branches:
  #      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone Source Code
        run: |
          git clone https://github.com/q215613905/TVBoxOS.git  bgcode
      - name: Add Sign Info
        run: |
          cd bgcode
          cp -f ${{ github.workspace }}/.github/bgcode.jks ./app/bgcode.jks
          sed -i '$a\RELEASE_STORE_FILE=./bgcode.jks'     ./gradle.properties
          sed -i '$a\RELEASE_KEY_ALIAS=bgcode'            ./gradle.properties
          sed -i '$a\RELEASE_STORE_PASSWORD=bgcode'       ./gradle.properties
          sed -i '$a\RELEASE_KEY_PASSWORD=bgcode'         ./gradle.properties


      - name: Build With Gradle
        run: |
          cd bgcode
          chmod +x gradlew
          ./gradlew assembleRelease --build-cache --parallel --daemon --warning-mode all

      - name: Prepare App
        run: |
            mkdir -p ${{ github.workspace }}/apk/
            for file in `find ~ -name "*.apk" -print`; do
              mv "$file" ${{ github.workspace }}/apk/
            done
      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
            name: bgcode
            path: ${{ github.workspace }}/apk/*
 
